
#File location of models.
model_path:
  coco_names: /Users/lalala/Documents/Upenn/CIS5810/final_project/models/coco.names
  vehicle_names: /Users/lalala/Documents/Upenn/CIS5810/final_project/models/coco.names
  # Use COCO for both target and surrounding detection
  licenseplate_names: /Users/lalala/Documents/Upenn/CIS5810/final_project/models/coco.names

  coco_yolo_cfg: /Users/lalala/Documents/Upenn/CIS5810/final_project/models/yolov3.cfg
  coco_yolo_weights: /Users/lalala/Documents/Upenn/CIS5810/final_project/models/yolo11s.pt

  vehicle_yolo_cfg: /Users/lalala/Documents/Upenn/CIS5810/final_project/models/yolov3.cfg
  vehicle_yolo_weights: /Users/lalala/Documents/Upenn/CIS5810/final_project/models/yolo11s.pt
  
  licenseplate_yolo_cfg: /Users/lalala/Documents/Upenn/CIS5810/final_project/models/yolov3.cfg
  licenseplate_yolo_weights: /Users/lalala/Documents/Upenn/CIS5810/final_project/models/yolo11s.pt

  MDE_model_path: /Users/lalala/Documents/Upenn/CIS5810/final_project/models/model-small.onnx

  crosswalk_names: /Users/lalala/Documents/Upenn/CIS5810/final_project/models/coco.names
  crosswalk_yolov5_pt: /Users/lalala/Documents/Upenn/CIS5810/final_project/models/yolov5_traffic_light.pt
  crosswalk_yolov5_onnx: /Users/lalala/Documents/Upenn/CIS5810/final_project/models/yolov5_traffic_light.onnx

 
#Camera information.
camera_information:
  # sensor_height_mm: 7.35                                                                                                 # Camera Sensor height in mm
  # sensor_height_px: 6048                                                                                                 # Camera feed native pixel resolution height   
  # focal_length: 14 
  sensor_height_mm: 5.5                                                                                                 # Camera Sensor height in mm
  sensor_height_px: 2160                                                                                                 # Camera feed native pixel resolution height   
  focal_length: 7.1 

#Target Object information
target_object:
  #target: cup
  target: person
  real_object_height: 1650                                                                                           # Target Object physical height in mm
